apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev
spec:
  template:
    spec:
      serviceAccountName: 26916718928-compute@developer.gserviceaccount.com
      containers:
        - image: 'asia-south1-docker.pkg.dev/prathmesh-cicd/flask-application/flask-application:${SHORT_SHA}'
