apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-application
description: main application pipeline
serialPipeline:
  stages:
    - targetId: dev
      profiles: 
        - dev
    - targetId: prod
      profiles: 
        - prod
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          canaryDeployment:
            percentages: [50]
            verify: false
