apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-application  # Pipeline name
description: Main application pipeline

serialPipeline:
  stages:
    - targetId: dev  # Development environment
      profiles:
        - dev
    - targetId: prod  # Production environment
      profiles:
        - prod
      strategy:
        canary:  # Canary deployment strategy
          runtimeConfig:
            cloudRun:  # Cloud Run runtime configuration
              automaticTrafficControl: true
          canaryDeployment:
            percentages: [50]  # Adjust Initial canary deployment percentage
