apiVersion: skaffold/v4beta7
kind: Config
metadata: 
  name: cloud-run-application

profiles:
  - name: dev  # Development profile
    manifests:
      rawYaml:
        - dev.yaml  # Dev deployment manifest

  - name: prod  # Production profile
    manifests:
      rawYaml:
        - prod.yaml  # Prod deployment manifest

deploy:
  cloudrun: {}  # Deploy to Cloud Run
