apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: development service
requireApproval: false
run:
  location: projects/prathmesh-cicd/locations/asia-south1

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: production service
requireApproval: true
run:
  location: projects/prathmesh-cicd/locations/asia-south1
